const seats = [
  {
    id: 13,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "U",
  },
  {
    id: 14,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "U",
  },
  {
    id: 15,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "U",
  },
  {
    id: 16,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "U",
  },
  {
    id: 17,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "U",
  },
  {
    id: 18,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "U",
  },
  {
    id: 19,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "U",
  },
  {
    id: 20,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "U",
  },
  {
    id: 21,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "U",
  },
  {
    id: 22,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "U",
  },
  {
    id: 23,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "U",
  },
  {
    id: 24,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "U",
  },
];

export default seats;
