const seats = [
  {
    id: 1,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "L",
  },
  {
    id: 2,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "L",
  },
  {
    id: 3,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "L",
  },
  {
    id: 4,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "L",
  },
  {
    id: 5,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "L",
  },
  {
    id: 6,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "L",
  },
  {
    id: 7,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "L",
  },
  {
    id: 8,
    type: "Standard",
    price: 100,
    description: "Regular seat",
    selected: false,
    deck: "L",
  },
  {
    id: 9,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "L",
  },
  {
    id: 10,
    type: "Window",
    price: 150,
    description: "Seat by the window",
    selected: false,
    deck: "L",
  },
  {
    id: 11,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "L",
  },
  {
    id: 12,
    type: "Reclining",
    price: 200,
    description: "Seat with extra reclining feature",
    selected: false,
    deck: "L",
  },
];

export default seats;
